version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/afrosnap_ai
      - JWT_SECRET=afrosnap-ai-super-secret-jwt-key-2024
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=afrosnap_ai
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: 